apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksronidemo-a80f"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aksronidemo-a80f"
  template:
    metadata:
      labels:
        app: "aksronidemo-a80f"
    spec:
      containers:
        - name: "aksronidemo-a80f"
          image: "crronidemo.azurecr.io/aksronidemo"
          ports:
          - containerPort: 80