on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: crronidemo.azurecr.io
        username: ${{ secrets.acr_crronidemo_username }}
        password: ${{ secrets.acr_crronidemo_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t crronidemo.azurecr.io/aksronidemo:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push crronidemo.azurecr.io/aksronidemo:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksronidemo_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-ronidemo | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-ronidemo`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-ronidemo
        container-registry-url: crronidemo.azurecr.io
        container-registry-username: ${{ secrets.acr_crronidemo_username }}
        container-registry-password: ${{ secrets.acr_crronidemo_password }}
        secret-name: aksronidemodockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-ronidemo
        manifests: |
          manifests/deployment-7.yml
          manifests/service-7.yml
        images: |
          crronidemo.azurecr.io/aksronidemo:${{ github.sha }}
        imagepullsecrets: |
          aksronidemodockerauth
